default_install_hook_types: [commit-msg, pre-commit, pre-push]
default_stages: [commit]
fail_fast: true
minimum_pre_commit_version: 2.21.0

repos:
  - repo: git@github.com:rhyscraig/pre-commit-hook.git
    rev: 1.0.0
    hooks:
      - id: common
      - id: secrets
      - id: terraform-module
