name: Validate and Deploy Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    name: Validate and Deploy to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for AWS OIDC authentication
      contents: read  # Required to check out the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        # This step sets up Node.js, which is needed for our validation tools (Prettier, ESLint)
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a current LTS version of Node.js
          cache: "npm" # Caches npm packages to speed up future runs

      - name: Install Project Dependencies
        # Installs the tools defined in your package.json (e.g., prettier, eslint)
        run: npm ci

      # --- VALIDATION STEPS ---
      - name: Check Code Formatting with Prettier
        # Verifies that all HTML, CSS, and JS files match the defined formatting rules
        run: npx prettier --check .

      - name: Lint JavaScript with ESLint
        # Analyzes JavaScript files for potential errors and bad practices
        run: npx eslint .

      # --- DEPLOYMENT STEPS ---
      - name: Configure AWS Credentials
        # Securely authenticates with your AWS account using an IAM role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767828739298:role/GitHubAction-AssumeRoleWithAction
          aws-region: eu-west-2

      - name: Deploy Files to S3
        # The 'sync' command is efficient. It only uploads changed files and can remove files
        # from the bucket that are no longer in your repository.
        run: |
          aws s3 sync . s3://www.craighoad.com/ --delete
