name: Deploy to S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Enter environment name
        required: true
        default: "prd"
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767828739298:role/GitHubAction-AssumeRoleWithAction
          aws-region: eu-west-2

      - name: Upload to S3
        run: |
          aws s3 cp . s3://tv.craighoad.com/ --recursive

      - name: Upload to S3
        run: |
          aws s3 cp ./tv/horror/2024/horror_tv_2024.json s3://banstore.craighoad.com/tv/horror/2024/horror_tv_2024.json
          aws s3 cp ./tv/thriller/2024/thriller_tv_2024.json s3://banstore.craighoad.com/tv/thriller/2024/thriller_tv_2024.json
